# CONTINUOUS INTEGRATION: PIPELINES

name: Piplelines_CI

on:
  push:
    branches: ['production', 'development']

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Use checkout to get the code onto the runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the dependences
      - name: Install dependencies
        run: npm install

      # Run the build
      - name: Build
        run: npm run build
